### ISSUE TITLE
Docker example in github page 529 no longer exists

### ISSUE THREAD

**Issue by sergiosolorzano** [PacktPublishing/Mastering-Embedded-Linux-Programming-Third-Edition#62]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/24430655/226855284-f1fba5bc-15dd-4f23-ad2a-61f14965aebc.png">

**Comment by fvasquez** [comment]
@sergiosolorzano the [link](https://github.com/tiangolo/uwsgi-nginx-flask-docker) works for me.

<img width="1904" alt="Screenshot 2023-03-22 at 9 16 32 PM" src="https://user-images.githubusercontent.com/905410/227102076-e29cf3f8-11cc-47c5-ad00-8a0f822a5868.png">

Is that the example you're talking about?

**Comment by sergiosolorzano** [comment]
Oh, apologies then ! I take the opportunity to thank you for the fantastic book you wrote, it's fascinating and it is really helping my learning !!
