### ISSUE TITLE
What should be in the root filesystem? command line errors 

### ISSUE THREAD

**Issue by Xylopyrographer** [PacktPublishing/Mastering-Embedded-Linux-Programming-Third-Edition#72]
Hi. Referencing MELP, 3rd ed, Chapter 5, _What should be in the root filesystem?_, page 133

The bottom part of the page shows a sequence of commands to copy the `*.so*` files into the `~/rootfs/bin` directory. The commands as given are in error as they copy the target file to a file called `~/rootfs/lib` instead of creating a copy of the file in the intended directory.

Had to:
- start from `~/rootfs`
- create the `lib` directory
- for each `cp -a...` line, replace `lib` with `./lib/`, like:
```
cd ~/rootfs && mkdir ./lib/
$ cp -a $SYSROOT/lib/ld-linux-armhf.so.3 ./lib/
.
.
.
```
Above the "Tip" box there is also the line: "Repeat this procedure for each program." It's a bit unclear what this is referring. Does it mean to copy the files (from the set of commands preceding the statement) to the `~/rootfs/bin` directory? If so we just did that so the statement is not needed?

Please note as well issue #71 also related to Chapter 5.

Thanks.

**Comment by vidhishapackt** [comment]
@fvasquez can you help with this ?

**Comment by fvasquez** [comment]
@vidhishapackt I have already been in contact with the reader regarding this and various other issues they reported. This issue is closely related to issue #70 which I've already addressed. I will respond when I have the specific steps to add to the errata to remedy this issue.

**Comment by fvasquez** [comment]
@Xylopyrographer the `cp -a ...` errors could be an artifact of your shell. The original commands work on my Ubuntu 24.04 LTS system which has `/bin/bash` as its shell.

```
frank@frank-nuc:~/rootfs$ echo $SHELL
/bin/bash
frank@frank-nuc:~/rootfs$ cp -a $SYSROOT/lib/ld-linux-aarch64.so.1 lib
frank@frank-nuc:~/rootfs$
```

> Above the "Tip" box there is also the line: "Repeat this procedure for each program." It's a bit unclear what this is referring. Does it mean to copy the files (from the set of commands preceding the statement) to the ~/rootfs/bin directory? If so we just did that so the statement is not needed?

By "each program" I mean each program you wish to include in your root filesystem. In this case we are only including `bin/busybox`. I understand this is unclear. Even I was confused but what I wrote here.

**Comment by fvasquez** [comment]
I repeated the exercise and responded to the reader's inquiries.
