### ISSUE TITLE
Building a Root Filesystem - command line error

### ISSUE THREAD

**Issue by Xylopyrographer** [PacktPublishing/Mastering-Embedded-Linux-Programming-Third-Edition#73]
Hi. Referencing MELP, 3rd ed, Chapter 5, _Building a Root Filesystem_, page 140.

In the _Booting the BeagleBone Black_ section,

When entering the U-Boot commands, there is the line
`fatload mmc 0:1 0x80f00000 am335x-boneblack.dtb fatload mmc 0:1 0x81000000 uRamdisk`

This is two commands and should be entered as:
`fatload mmc 0:1 0x80f00000 am335x-boneblack.dtb`
then
`fatload mmc 0:1 0x81000000 uRamdisk`

Thanks.

**Comment by fvasquez** [comment]
U-Boot erratum for page 140 added to README.
