### ISSUE TITLE
Chapter 4 - Page 105 - The svn export fails stating "'/raspberrypi/firmware/trunk/boot' path not found."

### ISSUE THREAD

**Issue by johan718** [PacktPublishing/Mastering-Embedded-Linux-Programming-Third-Edition#78]
While reading chapter 4 and attempting to export the boot folder with svn:

`svn export https://github.com/raspberrypi/firmware/trunk/boot`

The command failed and I received the following error messages:
```
svn: E170013: Unable to connect to a repository at URL 'https://github.com/raspberrypi/firmware/trunk/boot'
svn: E160013: '/raspberrypi/firmware/trunk/boot' path not found
```
Has a workaround been found for this by any chance?

**Comment by fvasquez** [comment]
Thank you, @johan718. Another reader recently reported this same issue. I think the Raspberry Pi firmware repo may have been converted from Subversion to Git. See current https://github.com/raspberrypi/firmware. I would try cloning that repo and copying the `boot` directory one level above the Linux kernel source tree (e.g. `..` from `linux-rpi`).

**Comment by fvasquez** [comment]
@johan718 here is what I advise readers to do now.

```
$ cd ~
$ git clone --depth=1 -b 1.20240529 https://github.com/raspberrypi/firmware.git firmware-rpi
$ mv firmware-rpi/boot .
$ rm -rf firmware-rpi
$ rm boot/kernel*
$ rm boot/*.dtb
$ rm boot/overlays/*.dtbo
```

I confirmed that the `1.20240529` tag of the firmware works with the current 6.6 LTS version of the kernel from https://github.com/raspberrypi/linux. That same tag may not be compatible with the 4.19 LTS version of the kernel used in the book.

**Comment by fvasquez** [comment]
Closing issue due to lack of response from opener.
